import requests
import base64

url = "https://jiotvapi.media.jio.com/playback/apis/v1/geturl"
Address = 'https://8WjUngqqHnpcjdkNbeCYcm5T:WaTCSLbVezb4MXXyUEzZm24h@in-mum.prod.surfshark.com:443'
proxy = {'https': Address}
payload = {
    "stream_type": "Seek",
    "channel_id": "180",
}
headers = {
    "devicetype": "phone",
    "os": "android",
    #"deviceId": "119a5a90s1fd4800",
    "channel_id": "180",
    "accesstoken": "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImF1dGhUb2tlbklkIjoiNzA4MjE5ZjMtNWY3ZS00N2I3LTk5MzYtMTRmYzFlN2E5ZDE4IiwidXNlcklkIjoiYmZlOTU4N2UtOGMxMS00NjA1LTg5MGYtZDAzODI5YThmNjgzIiwidXNlclR5cGUiOiJKSU8iLCJvcyI6ImlvcyIsImRldmljZVR5cGUiOiJwaG9uZSIsImFjY2Vzc0xldmVsIjoiOSIsImRldmljZUlkIjoiQkY4RjZBNTI4NTJFNEFBQTg5Qzc1RkI1QzgxREIwQjQiLCJleHRyYSI6IntcIm51bWJlclwiOlwic09PN2V3YmpjTEd5SDlNNFFURjJvVU1CdTdsQlBSdmpMbXJYYmVqWTJtTWZ3cFowaVd6bzJTRT1cIixcInBsYW5kZXRhaWxzXCI6e1wiUGFja2FnZUluZm9cIjpbe1wicGxhbmlkXCI6XCIxXCIsXCJzdWJzY3JpcHRpb25zdGFydFwiOjE2NjE5MzMwMTcsXCJzdWJzY3JpcHRpb25lbmRcIjoxODE0NTE0OTYwLFwicGxhbnR5cGVcIjpcIlwiLFwiYnVzaW5lc3NUeXBlXCI6XCJqaW9cIixcIm5vdGVzXCI6XCJcIn1dfSxcImpUb2tlblwiOlwiMWUzMGJhY2RiOGYyN2YzZDZkNzNmMGQyM2EzY2NhOGMuZTEwZDhjYTYzZGE4OWZmNzljMjUyZWRjZTUxOTMyNjY1MDYwZjNkNjVhODE0MjlmYTJhMjQ5ZDJmZDBkNDE4ZDE3ZDI4ZDBjYzc4YzlkNDljYWMxODg3NjkzYjJlNDRjNDk4MmFjNzA0ZWVlYThkMjhkYTFiOGRhYjAzZjAwOGU5ODJjNjI0Mjk0NTllMDRmY2Y5MWFlMzdhZjhlYWMxNjUyOThmNTk3YzI4ZmYyZTI4Njk5ZjRlNmRjZjczZGM5MzcxOTIzOGZlZjZiOWEzNjZmNjAxYzllOTFkZGE3MTZiMjhmNmQ2NjBhODA0YjZiZjY4OTM1YmVmMTg5N2U3MTgwMjVlMjY2MzExNDU4NTNmZWMyZDIyMTViNTg2MjI0NTAzZjM1YWE4ZGIxMzVlOGU5OGUyM2MwYmRlMDgwODkwNzYzMWJiMmZkMTYxNjdiZGY2YjExOWM2N2MyNWM4ZTg0M2FmZmVmNjAwM2FmYmYzNjNjMDBkNzA1ZDVmYmExZTYyNDcxMWE1OWQ3YjQ5NzAyY2I1ZWU4ZGM4NjhjYmFiNmUzMjRiNTI3MjY5YWQ2YzM2MDliYjVmYWQ5MjhhZmRiMTc0YTNlMGFhNTA2YjNlMGE1YzIxY2U3NGJjNjM0NjMzZTZmOGQwOTBjYjI2NjYyZmE5NThjMGEyZDBmZWRjZmVkOTcxODVjMGJhM2E2YzVlOWRjYTViMWE4MmRjNzBlN2E3NDU2YjI5NjI1MDhmODEwYmRjMjQ1YjQwNjRkZmY1ZDk0ZTg3MjMyOWUxNDAyNTY5YmI0YzA3M2Y2NDFkMmEzZjk0MWY0NmQyMTIzNTIxODU4ZWM0MzI3NjhjNjU3NGFmOGY0NDkyMjc1YzBlZWIzZmExZDQ5ZTkyMjFmMzRiN2IzNDMyMjhhNzM1NGM3M2JiYzdiMTk0YTZlYmI1YWYzZWQzNjFjZGFjNjlkODQ5MDU2NDM1YzQ5OGFiOVwiLFwidXNlckRldGFpbHNcIjpcImlOSjhzYXZLNGwxN1VyU2ZSdE54NFZhdnozMitvUVFVMGFXVXE4Rkp5MDI2ZHgwVUYrVzJtUndIVkYxN3hLeE0vblJQVGp3SE9PbkxQRUorOVF1dlo5a2ZDeXl2Vnl0bXBSbmwvSXFwNXgzdEpGc3ZOUlI1ZnRNWTI1L0pKcUl1Q2ZhQ2Zad3h5alJHcTlNL1dkM1REbDJhVXFPenRZQW9xbjgzcHNWc2VndG8rVVhVd0kwNFl5OWJvU0k4NTV0ZGNhbVlBSCt2ZVpqZFJvajk0NjF2RFV6T3h5Wkd0cmlzMEZMVitUdlhxTlhqeDZhOUhNejZySU1IQXhIM1BHMUN2dzBEWnplUzZ0THl3Zz09XCJ9Iiwic3Vic2NyaWJlcklkIjoiNTA2MDkwNDYxMSIsImFwcE5hbWUiOiJSSklMX0ppb1RWIiwidmVyc2lvbiI6InYyIn0sImV4cCI6MTc4NTYwNjk2MCwiaWF0IjoxNzgyOTc4OTYwfQ.Fnqp0K_r7-wpQUj4XvqnYlSmkeVm3UoNnEmOvTgdeb0F2JQLFgdZeLOfFtSV_BfzZvnxb-X7AS2yP4x9L2at2g",
}    
resp = requests.post(url, data=payload, proxies=proxy, headers=headers).json()
mpd = resp['mpd']['result']
mpd = "https://jiotvmblive.cdn.jio.com/" + mpd.split('/', 3)[-1]
stream = requests.get(mpd, proxies=proxy)
st = stream.headers.get('set-cookie').split(';')[0]
print(f'#EXTHTTP: {{"cookie": "{st}"}}')
